[project]
name = "myweather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.1",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
